config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get '/', to: 'home#index'

  resources :citizens
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
class Citizen < ApplicationRecord
  include TranslateEnum

  belongs_to :address
  belongs_to :phone
  has_many_attached :image, dependent: :destroy

  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  validates :email, format: { with: /\A([\w+-].?)+@[a-z\d-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :cpf, presence: true, uniqueness: true
  validate :cpf_must_be_valid
  validate :cns_must_be_valid
  validate :birthdate_must_be_valid

  scope :filter_by_name, ->(name) { where('name ILIKE :name', name: "%#{name}%") }
  scope :filter_by_cpf, ->(cpf) { where(cpf: cpf) }
  scope :filter_by_cns, ->(cns) { where(cns: cns) }
  scope :filter_by_email, ->(email) { where(email: email) }
  scope :filter_by_phone, ->(phone) { includes(:phone).where(phone: { number: phone }) }
  scope :filter_by_status, ->(status) { where(status: status) }

  translate_enum :status

  private

  def cpf_must_be_valid
    errors.add(:cpf, :cpf_must_be_valid) unless CPF.valid?(cpf)
  end

  def cns_must_be_valid
    return errors.add(:cns, :cns_must_be_valid) unless cns.present? && cns.length == 15

    sum = (0..14).sum { |i| cns[i].to_i * (15 - i) }

    errors.add(:cns, :cns_must_be_valid) unless (sum % 11).zero?
  end

  def birthdate_must_be_valid
    return errors.add(:cns, :birthdate_must_be_valid) unless birthdate <= Date.today - 5.years

    errors.add(:cns, :birthdate_must_be_valid) unless birthdate >= Date.today - 120.years
  end
end

app/models/country_code.rb
class CountryCode < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :country_code
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  def index
    if permitted_params_for_search.values.any?(&:present?)
      @citizens = filter_citizens
    else
      @citizens = Citizen.all
    end

    @page = params.permit(:page)
  end

  def new
    @country_codes = CountryCode.all
  end

  def create
    
  end

  private

  def permitted_params_for_search
    @permitted_params_for_search ||= params.permit(
      %i[name cpf cns email phone status page]
    )
  end

  def excluded_from_query
    %w[page]
  end

  def filter_citizens
    citizens = Citizen.where(nil)
    permitted_params_for_search.each do |key, value|
      next if excluded_from_query.include?(key)

      citizens = citizens.public_send("filter_by_#{key}", value) if value.present?
    end
    citizens
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def route_active?(action, class_name = 'active')
    current_page?(action) ? class_name : ''
  end
end

app/views/citizens/_citizen_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Email</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
  <% @citizens.each |citizen| do %>
    <tr>
      <th><%= citizen.name %></th>
      <th><%= CPF.new(citizen.cpf).formatted %></th>
      <th><%= citizen.email %></th>
      <th><%= citizen.status_translated %></th>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/citizens/index.html.erb
<div class="page-with-margin">

  <h4>Lista de munícipes</h4>

  <div class="card mb-4">

    <div class="card-body">
      <%= form_tag(citizens_path, method: :get, class: 'w-100') do %>

        <div class="row w-100">

          <div class="col-md-3 form-group">
            <%= label_tag :name, 'Nome' %>
            <input type="text" name="name" id="name" class="form-control" value="<%= params[:name] %>">
          </div>

          <div class="col-md-3 form-group">
            <%= label_tag :cpf, 'CPF' %>
            <input type="text" name="cpf" id="cpf" class="form-control" value="<%= params[:cpf] %>" pattern="\d{11}">
          </div>

          <div class="col-md-3 form-group">
            <%= label_tag :cns, 'CNS' %>
            <input type="text" name="cns" id="cns" class="form-control" value="<%= params[:cns] %>" pattern="\d{15}">
          </div>

          <div class="col-md-3 form-group">
            <%= label_tag :email, 'E-mail' %>
            <input type="email" name="email" id="email" class="form-control" value="<%= params[:email] %>">
          </div>

        </div>
        <div class="row w-100">

          <div class="col-md-3 form-group">
            <%= label_tag :phone, 'Telefone' %>
            <input type="phone" name="phone" id="phone" class="form-control" value="<%= params[:phone] %>">
          </div>

          <div class="col-md-3 form-group">
            <%= label_tag :status, 'Status' %>
            <select name="status" id="status" class="form-control" value="<%= params[:status] %>">
              <option value="">&lt;todos&gt;</option>
              <option value="active" <%= 'selected' if params[:status] == 'active' %>>Ativo</option>
              <option value="inactive" <%= 'selected' if params[:status] == 'inactive' %>>Inativo</option>
            </select>
          </div>

          <%= button_tag "Pesquisar", class: "btn btn-secondary align-self-end ml-auto" %>
        </div>

      <% end %>

    </div>

  </div>

  <% if @citizens.empty? %>
    <div style="margin-left: 15px">
      <p style="margin-left: 15px">Não foram encontrados resultados</p>
    </div>
  <% else %>
    <div style="margin-left: 15px; margin-bottom: 30px">

    <%= render partial: 'citizen_list' %>

    <%= paginate @citizens, theme: 'twitter-bootstrap-4' %>
  <% end %>

</div>

app/views/citizens/new.html.erb
<div class="page-with-margin">

  <h4>Criação de munícipes</h4>

  <div class="card mb-4">

    <div class="card-body">

    <%= form_for :citizen, url: citizens_path do |citizen_form| %>

      <div class="row w-100">
        <div class="col-md-3 form-group">
          <%= citizen_form.label :name, 'Nome' %>
          <%= citizen_form.text_field :name, class: 'form-control', required: true %>
        </div>

        <div class="col-md-3 form-group">
          <%= citizen_form.label :cpf, 'CPF' %>
          <%= citizen_form.text_field :cpf, class: 'form-control', pattern: '\\d{11}', required: true %>
        </div>

        <div class="col-md-3 form-group">
          <%= citizen_form.label :cns, 'CNS' %>
          <%= citizen_form.text_field :cns, class: 'form-control', pattern: '\\d{15}', required: true %>
        </div>

        <div class="col-md-3 form-group">
          <%= citizen_form.label :email, 'E-mail' %>
          <%= citizen_form.text_field :email, class: 'form-control', required: true %>
        </div>

      </div>

      <div class="row w-100">
        <%= citizen_form.fields_for :address do |address_fields| %>

          <div class="col-md-3 form-group">
            <%= address_fields.label :street, 'Longradouro' %>
            <%= address_fields.text_field :street, class: 'form-control', required: true %>
          </div>

          <div class="col-md-3 form-group">
            <%= address_fields.label :neighborhood, 'Bairro' %>
            <%= address_fields.text_field :neighborhood, class: 'form-control', required: true %>
          </div>

          <div class="col-md-3 form-group">
            <%= address_fields.label :uf, 'UF' %>
            <%= address_fields.text_field :uf, class: 'form-control', required: true %>
          </div>

          <div class="col-md-3 form-group">
            <%= address_fields.label :complement, 'Complemento' %>
            <%= address_fields.text_field :complement, class: 'form-control' %>
          </div>

        </div>
        <div class="row w-100">

          <div class="col-md-3 form-group">
            <%= address_fields.label :zip_code, 'Código postal' %>
            <%= address_fields.text_field :zip_code, class: 'form-control', required: true %>
          </div>

          <div class="col-md-3 form-group">
            <%= address_fields.label :igbe_code, 'Código IBGE' %>
            <%= address_fields.text_field :igbe_code, class: 'form-control' %>
          </div>

      <% end %>

      <%= citizen_form.fields_for :phone do |address_fields| %>

        <div class="col-md-3 form-group">
          <%= citizen_form.label :number, 'Telefone com DDD' %>
          <%= citizen_form.text_field :number, class: 'form-control', required: true %>
        </div>

        <div class="col-md-3 form-group">
          <%= citizen_form.label :country_code_id, 'Código do país' %>
          <%=
            citizen_form.select :country_code_id,
            options_from_collection_for_select(@country_codes, 'id', 'country_name'),
            class: 'form-control',
            required: true
          %>
        </div>

      <% end %>

      </div>

      <div class="row w-100">

        <div class="col-md-3 form-group">
          <%= citizen_form.label :birthdate, 'Data de nascimento' %>
          <%=
            citizen_form.date_field :birthdate,
            class: 'form-control',
            max: Date.today - 5.years,
            min: Date.today - 120.years
          %>
        </div>

        <div class="col-md-4 form-group">
          <%= citizen_form.label :photos, 'Fotos' %>
          <%=
            citizen_form.file_field :photos,
            multiple: true,
            accept: 'image/png,image/gif,image/jpeg',
            class: 'form-control'
          %>
        </div>

        <%= citizen_form.submit 'Salvar', class: 'btn btn-secondary align-self-end ml-auto' %>
      </div>

    <% end %>

    </div>

  </div>

</div>

app/views/home/index.html.erb
<div class="page-with-margin">

  <h4>Bem vindo ao nosso cadastro de cidadãos</h4>

  <h6>Fique à vontade para cadastrar cidadãos ou cidades</h6>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Citizen Catalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: 'partials/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Catálogo de cidadãos', root_path, class: 'navbar-brand' %>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item <%= route_active?(citizens_path) %>">
        <%= link_to 'Lista de cidadãos', citizens_path, class: 'nav-link' %>
      </li>

      <li class="nav-item <%= route_active?(new_citizen_path) %>">
        <%= link_to 'Criar cidadão', new_citizen_path, class: 'nav-link' %>
      </li>

    </ul>
  </div>
</nav>